schema_version = "1.0.0"

id = "secondary_language"
version = "1.1.0"
name = "Secondary Language"
tagline = "Quickly switch to secondary language"
maintainer = "mdlt7z"
type = "add-on"

website = "https://github.com/mdlt7z/secondary-language"
tags = ["User Interface"]

blender_version_min = "5.0.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 mdlt7z"]